# Site
name: "Ruter's Blog"
title: "Ruter's Blog"
description: "Share everything with you."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-117326683-2'
disqus: 'ruters-blog'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  ruter:
    name: Ruter
    display_name: "Ruter Lü"
    gravatar: 35760f50e53b982ffc5f6e4aafc0f58b
    email: i@ruterly.com
    web: https://ruterly.com
    twitter: https://twitter.com/ruterlv
    description: "Author of this blog, a Python & Odoo programmer."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
